name: Label Checker
on:
  issues:
    types: [labeled]

jobs:
  check-new-feature:
    runs-on: ubuntu-latest
    steps:
      - name: Check for 'new-feature' label
        if: contains(github.event.issue.labels.*.name, 'new-feature')
        run: |
          echo "New feature request detected!"
          echo "Issue Number: ${{ github.event.issue.number }}"
          # Can trigger additional automation here
